### ISSUE TITLE
include the rendering tool

### ISSUE THREAD

**Issue by dvincentwest** [eggachecat/jycm#1]
will you consider including the rendering tool shown in the examples as part of the repository?  I think that feature really highlights what people are looking for in a tool like this, and you might get some serious traction in the project.  It looks like its HTML based, and I can already see some great uses as a plugin for apps that allow you to readily examine data structures.  Will you consider including this soon?

**Comment by eggachecat** [comment]
@dvincentwest ok sure! I will release that in days

**Comment by eggachecat** [comment]
@dvincentwest Hi there's a beta version [react-jycm-viewer](https://github.com/eggachecat/react-jycm-viewer) if you are using react

**Comment by eggachecat** [comment]
@dvincentwest  Hi I just updated the readme and release a version on npm. And here comes a example project https://github.com/eggachecat/react-jycm-viewer-example!

**Comment by eggachecat** [comment]
@dvincentwest  Hi! Just for your reference~

Now jycm supports result-visualization 

- upgrade jycm
```bash
pip install jycm --upgrade
```
- then you can visualize the results by
```
python -m jycm --show \
--left="{\"normal-string\":\"aaaaa\",\"ignore_me-string\":\"aaaaa\",\"normal-list-1\":[{\"val\":1},{\"val\":2},{\"val\":3},{\"val\":4},{\"val\":5}],\"set_in_set\":[{\"id\":1,\"label\":\"label:1\",\"set\":[1,2,3,4,5]},{\"id\":2,\"label\":\"label:2\",\"set\":[4,5,6,7,8]}]}" \
--right="{\"normal-string\":\"bbbbb\",\"ignore_me-string\":\"bbbbb\",\"normal-list-1\":[{\"val\":1},{\"val\":9},{\"val\":3},{\"val\":8},{\"what\":5}],\"set_in_set\":[{\"id\":2,\"label\":\"label:2\",\"set\":[6,5,4,7]},{\"id\":1,\"label\":\"label:1\",\"set\":[3,2,1,4,8,9]}]}" \
--rules="[{\"operation\":\"ignore\",\"value\":\"^ignore_me.*\"},{\"value\":\"^set_in_set$\",\"operation\":\"operator:list:ignoreOrder\"},{\"value\":\"set_in_set->\\\\[\\\\d+\\\\]->set\",\"operation\":\"operator:list:ignoreOrder\"}]" 
```
more information can be found the updated README~
thanks for your suggestion!

**Comment by dvincentwest** [comment]
Sweet
