### ISSUE TITLE
Can the original names of the left and right files be displayed in the browser instead of left and right

### ISSUE THREAD

**Issue by jintao233** [eggachecat/jycm#10]
Is it possible to display the original names of left and right files in the browser instead of left and right

**Comment by eggachecat** [comment]
Hi @jintao233 I think this is a good idea! I will work on it.

**Comment by eggachecat** [comment]
@jintao233 
Hi! Now jycm use the file names as default titles!
Please upgrade jycm
```bash
pip install jycm --upgrade
```
Let me know if something go wrong!
