### ISSUE TITLE
Lowercase true and false, and null values in JSON throw a NameError

### ISSUE THREAD

**Issue by scotbu** [eggachecat/jycm#11]
Edit: This should be closed as a non-issue. See my comment below.

The [JSON spec](https://www.json.org/json-en.html) indicates that the lower case true and lower case false should be used, and `null` should be used for null values. (I don't mean to argue whether this is right or wrong, just that it's what the spec says and it occurs in many JSON files that I work with.)

jycm accepts uppercase False and uppercase True but not lower case. The output in the visualizer shows lower case even though the raw JSON contains uppercase.

In example 1 if an all lower case true and false, is added, the module will throw `NameError: name 'false' is not defined`.

A value of `null` in the JSON file will throw a similar error

Version info:
Window 10
Python 3.8.2 

```python
from jycm.helper import dump_html_output, open_url
from jycm.jycm import YouchamaJsonDiffer


def run_example_1():

    left = {
        "a": 1,
        "b": 2,
        "d": "12345",
        "f_upper": False,
        "f_lower": false,
        "null_test": null,
        "e": [
            {
                "x": 1,
                "y": 1
            },
            {
                "x": 2,
                "y": 2
            },
            {
                "x": 3,
                "y": 3
            },
            {
                "x": 4,
                "y": 4
            },
        ]
    }

    right = {
        "a": 1,
        "b": 3,
        "c": 4,
        "f_upper": True,
        "f_lower": true,
        "null_test": 0,
        "e": [
            {
                "x": 0,
                "y": 1
            },
            {
                "x": 2,
                "y": 2
            },
            {
                "x": 3,
                "y": 3
            },
            {
                "x": 5,
                "y": 5
            },
        ]
    }

    ycm = YouchamaJsonDiffer(left, right)
    ycm.diff()  # you have to call this
    diff_result = ycm.to_dict()

    # you can find generated html in the folder
    output_dir = "c:/temp/jycm-example-1"
    # you can directly view it by clicking the index.html file inside the folder
    url = dump_html_output(left, right, diff_result, output_dir)

    # if you want to open it from python
    open_url(url)


if __name__ == '__main__':
    run_example_1()
```

**Comment by scotbu** [comment]
This is my mistake and should be closed as a non-issue. It is simply a difference in how JSON and Python name booleans and null values. 

```
Python         JSON
True           true
False          false
None           null
```

I tried the example with None and also by converting a JSON string containing true, false and null using json.dumps() and it works correctly.

Sorry about logging it as as an issue,

**Comment by eggachecat** [comment]
Hi @scotbu don’t worry! We are all learning something here :). I have never read the spec before and now I do! Feel free to discuss anything here. Welcome to the open source world!
