### ISSUE TITLE
Dependencies are resolved too slow when adding jycm to a poetry project

### ISSUE THREAD

**Issue by aryaphan** [eggachecat/jycm#16]
Hi there,

I'm using jycm in a poetry project and it takes ~4mins to resolve dependencies for jycm. For example:
![image](https://github.com/eggachecat/jycm/assets/65004624/613bffcc-0912-4ceb-b479-c2c851a580ac)

I was suspecting that it could be because there is no constraint on `numpy` version in `requirements.txt` so it took a long time to search for a suitable numpy version? Could you please let me know if there is a way to speed it up? Thanks!

**Comment by eggachecat** [comment]
Hi @aryaphan, this seems to be an unusual issue (did some search on slow-installation-on-mac, no luck). 
You're right, there isn't a specific numpy version. Could you try running `pip install numpy`? If this process is also slow, it might be related to PIP itself. 

If you're experiencing network issues (for example, if you're in China, you might want to use a proxy like `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple`). 

I personally use Linux and Windows, so I'm unable to replicate and debug this issue on a Mac.

**Comment by aryaphan** [comment]
All good. It seemed to resolve itself for me now. Probably network issues. Thanks for your help!
