### ISSUE TITLE
Command line arguments limit

### ISSUE THREAD

**Issue by misaunde** [eggachecat/jycm#3]
Could you make optional parameters that take a filename? Instead of only being able to pass in raw json?

I'm running into an issue where it errors out because my json objects are too big to pass in as command line args.
Reference: https://serverfault.com/questions/69430/what-is-the-maximum-length-of-a-command-line-in-mac-os-x 

Error message: ``OSError: [Errno 7] Argument list too long: '/bin/sh'``

Seems like the easy fix would be to accept json filenames as input args.

**Comment by eggachecat** [comment]
that's a very good idea!

**Comment by eggachecat** [comment]
@misaunde Hi I just update the package
you can upgrade the package by 
```bash
pip install jycm --upgrade
```
now it supports something like
```bash
python -m jycm --show  --left_file /xxxx/your_left.json --right_file ~/xxxx/your_right.json
```

**Comment by misaunde** [comment]
@eggachecat thank you thank you
Just tested it, and it works great!
