### ISSUE TITLE
The code examples do not open up the graph/diff view for me

### ISSUE THREAD

**Issue by misaunde** [eggachecat/jycm#4]
I really like the diff view aspect of your project, and I would like to get that part working.

Is there an additional piece of code or config required to open up the diff view from inside a python script?
The documented code examples do not open the diff view for me. Reference: https://github.com/eggachecat/jycm#code 

So far, only executing the examples for the command line open up the graph/diff view for me, but unfortunately, going that route I run into this other bug: https://github.com/eggachecat/jycm/issues/3 

 Thoughts?

**Comment by eggachecat** [comment]
@misaunde hi! 
the code making use of [viewer](https://github.com/eggachecat/react-jycm-viewer) is from here https://github.com/eggachecat/jycm/blob/master/jycm/__main__.py#L62
let me know if it helps!

**Comment by eggachecat** [comment]
I'll include the the rendering code soon~

**Comment by eggachecat** [comment]
@misaunde Hi I just update the package
you can upgrade the package by 
```bash
pip install jycm --upgrade
```
now it supports making html and openning url from your own python script:
```bash
from jycm.helper import make_ignore_order_func
from jycm.jycm import YouchamaJsonDiffer
from jycm.helper import dump_html_output, open_url
from jycm.jycm import YouchamaJsonDiffer

left = {
    "a": 1,
    "b": 2,
    "d": "12345",
    "f": False,
    "e": [
        {"x": 1, "y": 1},
        {"x": 2, "y": 2},
        {"x": 3, "y": 3},
        {"x": 4, "y": 4},
    ]
}

right = {
    "a": 1,
    "b": 3,
    "c": 4,
    "f": True,
    "e": [
        {"x": 0, "y": 1},
        {"x": 2, "y": 2},
        {"x": 3, "y": 3},
        {"x": 5, "y": 5},
    ]
}

ycm = YouchamaJsonDiffer(left, right)
ycm.diff()
diff_result = ycm.to_dict()

# you can find generated html in the folder
output_dir = "/Users/xxx/jycm-example-1"
# you can directly view it by clicking the index.html file inside the folder
url = dump_html_output(left, right, diff_result, output_dir)

# if you want to open it from python
open_url(url)

```

**Comment by misaunde** [comment]
@eggachecat that looks wonderful.

It took me a second to realize I couldn't use the relative path (I had to use the absolute path), but other than that, this works great now. 

This library is just what I was looking for. Thank you.
