### ISSUE TITLE
Update docs to include what nopairs is for. 

### ISSUE THREAD

**Issue by TonisPiip** [eggachecat/jycm#6]
both `ycm.to_dict(no_pairs=True)` and `ycm.to_dict()` are used in the doc. However the return of what the pairs are isn't explained anywhere. 

I would suggest updating the readme to include either: 

* A to_dict section, going over the basic options  
* Just a note explaining what pairs are, and why you would want to use ` no_pairs=True`

**Comment by eggachecat** [comment]
Thanks @TonisPiip , Great suggestion, will include it soon!
