### ISSUE TITLE
to_dict returning {} when there is diff, but diff() has not been called.

### ISSUE THREAD

**Issue by TonisPiip** [eggachecat/jycm#7]
when calling to_dict but not calling diff always returns {}.

However it should either

* Call diff() before looping over the events if it hasn't been done before
* erorr
* have a kwarg arg for to_dict, which will call diff().

Currently if I know there is a diff and I just want to get get the dict, I have to do 3 lines of code. 

Ideally it should be possible to just say either:

`differ(left, right).diff().to_dict()` or 
`differ(left, right)to_dict(run=True)` or just `differ(left, right).to_dict()`

**Comment by eggachecat** [comment]
Hi @TonisPiip this is a great suggestion! Will be implemented soon
